/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TwoFactorRouteImport } from './routes/two-factor'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopProductsRouteImport } from './routes/shop.products'
import { Route as ShopCheckoutRouteImport } from './routes/shop.checkout'
import { Route as ShopAccountRouteImport } from './routes/shop.account'
import { Route as AuthenticatedWarehousesRouteImport } from './routes/_authenticated/warehouses'
import { Route as AuthenticatedVendorsRouteImport } from './routes/_authenticated/vendors'
import { Route as AuthenticatedUserRolesRouteImport } from './routes/_authenticated/user-roles'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated/suppliers'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRlsTestRouteImport } from './routes/_authenticated/rls-test'
import { Route as AuthenticatedReceivingRouteImport } from './routes/_authenticated/receiving'
import { Route as AuthenticatedPurchasesRouteImport } from './routes/_authenticated/purchases'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedMembersRouteImport } from './routes/_authenticated/members'
import { Route as AuthenticatedInventoryTxRouteImport } from './routes/_authenticated/inventory-tx'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedDealersRouteImport } from './routes/_authenticated/dealers'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedCategoriesRouteImport } from './routes/_authenticated/categories'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ShopAccountIndexRouteImport } from './routes/shop.account.index'
import { Route as AuthenticatedFinanceIndexRouteImport } from './routes/_authenticated/finance.index'
import { Route as ShopProductIdRouteImport } from './routes/shop.product.$id'
import { Route as ShopCategorySlugRouteImport } from './routes/shop.category.$slug'
import { Route as ShopAccountProfileRouteImport } from './routes/shop.account.profile'
import { Route as ShopAccountOrdersRouteImport } from './routes/shop.account.orders'
import { Route as ShopAccountAddressesRouteImport } from './routes/shop.account.addresses'
import { Route as AuthenticatedProductsProductIdRouteImport } from './routes/_authenticated/products.$productId'
import { Route as AuthenticatedFinanceTransactionsRouteImport } from './routes/_authenticated/finance.transactions'
import { Route as AuthenticatedFinanceReceivableRouteImport } from './routes/_authenticated/finance.receivable'
import { Route as AuthenticatedFinancePayableRouteImport } from './routes/_authenticated/finance.payable'
import { Route as AuthenticatedFinanceBankAccountsRouteImport } from './routes/_authenticated/finance.bank-accounts'
import { Route as AuthenticatedB2bAccountsRouteImport } from './routes/_authenticated/b2b.accounts'
import { Route as AuthenticatedAdminSecurityRouteImport } from './routes/_authenticated/admin.security'
import { Route as AuthenticatedAdminRoleManagerRouteImport } from './routes/_authenticated/admin.role-manager'
import { Route as AuthenticatedAdminCompaniesRouteImport } from './routes/_authenticated/admin.companies'
import { Route as AuthenticatedAdminAuditLogsRouteImport } from './routes/_authenticated/admin.audit-logs'
import { Route as ShopAccountOrdersIdRouteImport } from './routes/shop.account.orders.$id'
import { Route as AuthenticatedB2bAccountsIdRouteImport } from './routes/_authenticated/b2b.accounts.$id'

const TwoFactorRoute = TwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopProductsRoute = ShopProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCheckoutRoute = ShopCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => ShopRoute,
} as any)
const ShopAccountRoute = ShopAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ShopRoute,
} as any)
const AuthenticatedWarehousesRoute = AuthenticatedWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVendorsRoute = AuthenticatedVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUserRolesRoute = AuthenticatedUserRolesRouteImport.update({
  id: '/user-roles',
  path: '/user-roles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRlsTestRoute = AuthenticatedRlsTestRouteImport.update({
  id: '/rls-test',
  path: '/rls-test',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReceivingRoute = AuthenticatedReceivingRouteImport.update({
  id: '/receiving',
  path: '/receiving',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPurchasesRoute = AuthenticatedPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMembersRoute = AuthenticatedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInventoryTxRoute =
  AuthenticatedInventoryTxRouteImport.update({
    id: '/inventory-tx',
    path: '/inventory-tx',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDealersRoute = AuthenticatedDealersRouteImport.update({
  id: '/dealers',
  path: '/dealers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCategoriesRoute = AuthenticatedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ShopAccountIndexRoute = ShopAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopAccountRoute,
} as any)
const AuthenticatedFinanceIndexRoute =
  AuthenticatedFinanceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const ShopProductIdRoute = ShopProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCategorySlugRoute = ShopCategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => ShopRoute,
} as any)
const ShopAccountProfileRoute = ShopAccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ShopAccountRoute,
} as any)
const ShopAccountOrdersRoute = ShopAccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ShopAccountRoute,
} as any)
const ShopAccountAddressesRoute = ShopAccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => ShopAccountRoute,
} as any)
const AuthenticatedProductsProductIdRoute =
  AuthenticatedProductsProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => AuthenticatedProductsRoute,
  } as any)
const AuthenticatedFinanceTransactionsRoute =
  AuthenticatedFinanceTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinanceReceivableRoute =
  AuthenticatedFinanceReceivableRouteImport.update({
    id: '/receivable',
    path: '/receivable',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinancePayableRoute =
  AuthenticatedFinancePayableRouteImport.update({
    id: '/payable',
    path: '/payable',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinanceBankAccountsRoute =
  AuthenticatedFinanceBankAccountsRouteImport.update({
    id: '/bank-accounts',
    path: '/bank-accounts',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedB2bAccountsRoute =
  AuthenticatedB2bAccountsRouteImport.update({
    id: '/b2b/accounts',
    path: '/b2b/accounts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSecurityRoute =
  AuthenticatedAdminSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRoleManagerRoute =
  AuthenticatedAdminRoleManagerRouteImport.update({
    id: '/role-manager',
    path: '/role-manager',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCompaniesRoute =
  AuthenticatedAdminCompaniesRouteImport.update({
    id: '/companies',
    path: '/companies',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditLogsRoute =
  AuthenticatedAdminAuditLogsRouteImport.update({
    id: '/audit-logs',
    path: '/audit-logs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ShopAccountOrdersIdRoute = ShopAccountOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ShopAccountOrdersRoute,
} as any)
const AuthenticatedB2bAccountsIdRoute =
  AuthenticatedB2bAccountsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedB2bAccountsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRouteWithChildren
  '/two-factor': typeof TwoFactorRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/categories': typeof AuthenticatedCategoriesRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dealers': typeof AuthenticatedDealersRoute
  '/finance': typeof AuthenticatedFinanceRouteWithChildren
  '/inventory': typeof AuthenticatedInventoryRoute
  '/inventory-tx': typeof AuthenticatedInventoryTxRoute
  '/members': typeof AuthenticatedMembersRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/products': typeof AuthenticatedProductsRouteWithChildren
  '/purchases': typeof AuthenticatedPurchasesRoute
  '/receiving': typeof AuthenticatedReceivingRoute
  '/rls-test': typeof AuthenticatedRlsTestRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/user-roles': typeof AuthenticatedUserRolesRoute
  '/vendors': typeof AuthenticatedVendorsRoute
  '/warehouses': typeof AuthenticatedWarehousesRoute
  '/shop/account': typeof ShopAccountRouteWithChildren
  '/shop/checkout': typeof ShopCheckoutRoute
  '/shop/products': typeof ShopProductsRoute
  '/shop/': typeof ShopIndexRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/admin/role-manager': typeof AuthenticatedAdminRoleManagerRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/b2b/accounts': typeof AuthenticatedB2bAccountsRouteWithChildren
  '/finance/bank-accounts': typeof AuthenticatedFinanceBankAccountsRoute
  '/finance/payable': typeof AuthenticatedFinancePayableRoute
  '/finance/receivable': typeof AuthenticatedFinanceReceivableRoute
  '/finance/transactions': typeof AuthenticatedFinanceTransactionsRoute
  '/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/shop/account/addresses': typeof ShopAccountAddressesRoute
  '/shop/account/orders': typeof ShopAccountOrdersRouteWithChildren
  '/shop/account/profile': typeof ShopAccountProfileRoute
  '/shop/category/$slug': typeof ShopCategorySlugRoute
  '/shop/product/$id': typeof ShopProductIdRoute
  '/finance/': typeof AuthenticatedFinanceIndexRoute
  '/shop/account/': typeof ShopAccountIndexRoute
  '/b2b/accounts/$id': typeof AuthenticatedB2bAccountsIdRoute
  '/shop/account/orders/$id': typeof ShopAccountOrdersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/two-factor': typeof TwoFactorRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/categories': typeof AuthenticatedCategoriesRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dealers': typeof AuthenticatedDealersRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/inventory-tx': typeof AuthenticatedInventoryTxRoute
  '/members': typeof AuthenticatedMembersRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/products': typeof AuthenticatedProductsRouteWithChildren
  '/purchases': typeof AuthenticatedPurchasesRoute
  '/receiving': typeof AuthenticatedReceivingRoute
  '/rls-test': typeof AuthenticatedRlsTestRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/user-roles': typeof AuthenticatedUserRolesRoute
  '/vendors': typeof AuthenticatedVendorsRoute
  '/warehouses': typeof AuthenticatedWarehousesRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/shop/products': typeof ShopProductsRoute
  '/shop': typeof ShopIndexRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/admin/role-manager': typeof AuthenticatedAdminRoleManagerRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/b2b/accounts': typeof AuthenticatedB2bAccountsRouteWithChildren
  '/finance/bank-accounts': typeof AuthenticatedFinanceBankAccountsRoute
  '/finance/payable': typeof AuthenticatedFinancePayableRoute
  '/finance/receivable': typeof AuthenticatedFinanceReceivableRoute
  '/finance/transactions': typeof AuthenticatedFinanceTransactionsRoute
  '/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/shop/account/addresses': typeof ShopAccountAddressesRoute
  '/shop/account/orders': typeof ShopAccountOrdersRouteWithChildren
  '/shop/account/profile': typeof ShopAccountProfileRoute
  '/shop/category/$slug': typeof ShopCategorySlugRoute
  '/shop/product/$id': typeof ShopProductIdRoute
  '/finance': typeof AuthenticatedFinanceIndexRoute
  '/shop/account': typeof ShopAccountIndexRoute
  '/b2b/accounts/$id': typeof AuthenticatedB2bAccountsIdRoute
  '/shop/account/orders/$id': typeof ShopAccountOrdersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRouteWithChildren
  '/two-factor': typeof TwoFactorRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/categories': typeof AuthenticatedCategoriesRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dealers': typeof AuthenticatedDealersRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRouteWithChildren
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/inventory-tx': typeof AuthenticatedInventoryTxRoute
  '/_authenticated/members': typeof AuthenticatedMembersRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/products': typeof AuthenticatedProductsRouteWithChildren
  '/_authenticated/purchases': typeof AuthenticatedPurchasesRoute
  '/_authenticated/receiving': typeof AuthenticatedReceivingRoute
  '/_authenticated/rls-test': typeof AuthenticatedRlsTestRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRoute
  '/_authenticated/user-roles': typeof AuthenticatedUserRolesRoute
  '/_authenticated/vendors': typeof AuthenticatedVendorsRoute
  '/_authenticated/warehouses': typeof AuthenticatedWarehousesRoute
  '/shop/account': typeof ShopAccountRouteWithChildren
  '/shop/checkout': typeof ShopCheckoutRoute
  '/shop/products': typeof ShopProductsRoute
  '/shop/': typeof ShopIndexRoute
  '/_authenticated/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/_authenticated/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/_authenticated/admin/role-manager': typeof AuthenticatedAdminRoleManagerRoute
  '/_authenticated/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/_authenticated/b2b/accounts': typeof AuthenticatedB2bAccountsRouteWithChildren
  '/_authenticated/finance/bank-accounts': typeof AuthenticatedFinanceBankAccountsRoute
  '/_authenticated/finance/payable': typeof AuthenticatedFinancePayableRoute
  '/_authenticated/finance/receivable': typeof AuthenticatedFinanceReceivableRoute
  '/_authenticated/finance/transactions': typeof AuthenticatedFinanceTransactionsRoute
  '/_authenticated/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/shop/account/addresses': typeof ShopAccountAddressesRoute
  '/shop/account/orders': typeof ShopAccountOrdersRouteWithChildren
  '/shop/account/profile': typeof ShopAccountProfileRoute
  '/shop/category/$slug': typeof ShopCategorySlugRoute
  '/shop/product/$id': typeof ShopProductIdRoute
  '/_authenticated/finance/': typeof AuthenticatedFinanceIndexRoute
  '/shop/account/': typeof ShopAccountIndexRoute
  '/_authenticated/b2b/accounts/$id': typeof AuthenticatedB2bAccountsIdRoute
  '/shop/account/orders/$id': typeof ShopAccountOrdersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/shop'
    | '/two-factor'
    | '/admin'
    | '/categories'
    | '/customers'
    | '/dashboard'
    | '/dealers'
    | '/finance'
    | '/inventory'
    | '/inventory-tx'
    | '/members'
    | '/orders'
    | '/products'
    | '/purchases'
    | '/receiving'
    | '/rls-test'
    | '/settings'
    | '/suppliers'
    | '/user-roles'
    | '/vendors'
    | '/warehouses'
    | '/shop/account'
    | '/shop/checkout'
    | '/shop/products'
    | '/shop/'
    | '/admin/audit-logs'
    | '/admin/companies'
    | '/admin/role-manager'
    | '/admin/security'
    | '/b2b/accounts'
    | '/finance/bank-accounts'
    | '/finance/payable'
    | '/finance/receivable'
    | '/finance/transactions'
    | '/products/$productId'
    | '/shop/account/addresses'
    | '/shop/account/orders'
    | '/shop/account/profile'
    | '/shop/category/$slug'
    | '/shop/product/$id'
    | '/finance/'
    | '/shop/account/'
    | '/b2b/accounts/$id'
    | '/shop/account/orders/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/two-factor'
    | '/admin'
    | '/categories'
    | '/customers'
    | '/dashboard'
    | '/dealers'
    | '/inventory'
    | '/inventory-tx'
    | '/members'
    | '/orders'
    | '/products'
    | '/purchases'
    | '/receiving'
    | '/rls-test'
    | '/settings'
    | '/suppliers'
    | '/user-roles'
    | '/vendors'
    | '/warehouses'
    | '/shop/checkout'
    | '/shop/products'
    | '/shop'
    | '/admin/audit-logs'
    | '/admin/companies'
    | '/admin/role-manager'
    | '/admin/security'
    | '/b2b/accounts'
    | '/finance/bank-accounts'
    | '/finance/payable'
    | '/finance/receivable'
    | '/finance/transactions'
    | '/products/$productId'
    | '/shop/account/addresses'
    | '/shop/account/orders'
    | '/shop/account/profile'
    | '/shop/category/$slug'
    | '/shop/product/$id'
    | '/finance'
    | '/shop/account'
    | '/b2b/accounts/$id'
    | '/shop/account/orders/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/shop'
    | '/two-factor'
    | '/_authenticated/admin'
    | '/_authenticated/categories'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/dealers'
    | '/_authenticated/finance'
    | '/_authenticated/inventory'
    | '/_authenticated/inventory-tx'
    | '/_authenticated/members'
    | '/_authenticated/orders'
    | '/_authenticated/products'
    | '/_authenticated/purchases'
    | '/_authenticated/receiving'
    | '/_authenticated/rls-test'
    | '/_authenticated/settings'
    | '/_authenticated/suppliers'
    | '/_authenticated/user-roles'
    | '/_authenticated/vendors'
    | '/_authenticated/warehouses'
    | '/shop/account'
    | '/shop/checkout'
    | '/shop/products'
    | '/shop/'
    | '/_authenticated/admin/audit-logs'
    | '/_authenticated/admin/companies'
    | '/_authenticated/admin/role-manager'
    | '/_authenticated/admin/security'
    | '/_authenticated/b2b/accounts'
    | '/_authenticated/finance/bank-accounts'
    | '/_authenticated/finance/payable'
    | '/_authenticated/finance/receivable'
    | '/_authenticated/finance/transactions'
    | '/_authenticated/products/$productId'
    | '/shop/account/addresses'
    | '/shop/account/orders'
    | '/shop/account/profile'
    | '/shop/category/$slug'
    | '/shop/product/$id'
    | '/_authenticated/finance/'
    | '/shop/account/'
    | '/_authenticated/b2b/accounts/$id'
    | '/shop/account/orders/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShopRoute: typeof ShopRouteWithChildren
  TwoFactorRoute: typeof TwoFactorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/two-factor': {
      id: '/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof TwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/products': {
      id: '/shop/products'
      path: '/products'
      fullPath: '/shop/products'
      preLoaderRoute: typeof ShopProductsRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/checkout': {
      id: '/shop/checkout'
      path: '/checkout'
      fullPath: '/shop/checkout'
      preLoaderRoute: typeof ShopCheckoutRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/account': {
      id: '/shop/account'
      path: '/account'
      fullPath: '/shop/account'
      preLoaderRoute: typeof ShopAccountRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_authenticated/warehouses': {
      id: '/_authenticated/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof AuthenticatedWarehousesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vendors': {
      id: '/_authenticated/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AuthenticatedVendorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/user-roles': {
      id: '/_authenticated/user-roles'
      path: '/user-roles'
      fullPath: '/user-roles'
      preLoaderRoute: typeof AuthenticatedUserRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rls-test': {
      id: '/_authenticated/rls-test'
      path: '/rls-test'
      fullPath: '/rls-test'
      preLoaderRoute: typeof AuthenticatedRlsTestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/receiving': {
      id: '/_authenticated/receiving'
      path: '/receiving'
      fullPath: '/receiving'
      preLoaderRoute: typeof AuthenticatedReceivingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchases': {
      id: '/_authenticated/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AuthenticatedPurchasesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/members': {
      id: '/_authenticated/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthenticatedMembersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory-tx': {
      id: '/_authenticated/inventory-tx'
      path: '/inventory-tx'
      fullPath: '/inventory-tx'
      preLoaderRoute: typeof AuthenticatedInventoryTxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dealers': {
      id: '/_authenticated/dealers'
      path: '/dealers'
      fullPath: '/dealers'
      preLoaderRoute: typeof AuthenticatedDealersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/categories': {
      id: '/_authenticated/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/shop/account/': {
      id: '/shop/account/'
      path: '/'
      fullPath: '/shop/account/'
      preLoaderRoute: typeof ShopAccountIndexRouteImport
      parentRoute: typeof ShopAccountRoute
    }
    '/_authenticated/finance/': {
      id: '/_authenticated/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof AuthenticatedFinanceIndexRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/shop/product/$id': {
      id: '/shop/product/$id'
      path: '/product/$id'
      fullPath: '/shop/product/$id'
      preLoaderRoute: typeof ShopProductIdRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/category/$slug': {
      id: '/shop/category/$slug'
      path: '/category/$slug'
      fullPath: '/shop/category/$slug'
      preLoaderRoute: typeof ShopCategorySlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/account/profile': {
      id: '/shop/account/profile'
      path: '/profile'
      fullPath: '/shop/account/profile'
      preLoaderRoute: typeof ShopAccountProfileRouteImport
      parentRoute: typeof ShopAccountRoute
    }
    '/shop/account/orders': {
      id: '/shop/account/orders'
      path: '/orders'
      fullPath: '/shop/account/orders'
      preLoaderRoute: typeof ShopAccountOrdersRouteImport
      parentRoute: typeof ShopAccountRoute
    }
    '/shop/account/addresses': {
      id: '/shop/account/addresses'
      path: '/addresses'
      fullPath: '/shop/account/addresses'
      preLoaderRoute: typeof ShopAccountAddressesRouteImport
      parentRoute: typeof ShopAccountRoute
    }
    '/_authenticated/products/$productId': {
      id: '/_authenticated/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AuthenticatedProductsProductIdRouteImport
      parentRoute: typeof AuthenticatedProductsRoute
    }
    '/_authenticated/finance/transactions': {
      id: '/_authenticated/finance/transactions'
      path: '/transactions'
      fullPath: '/finance/transactions'
      preLoaderRoute: typeof AuthenticatedFinanceTransactionsRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/receivable': {
      id: '/_authenticated/finance/receivable'
      path: '/receivable'
      fullPath: '/finance/receivable'
      preLoaderRoute: typeof AuthenticatedFinanceReceivableRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/payable': {
      id: '/_authenticated/finance/payable'
      path: '/payable'
      fullPath: '/finance/payable'
      preLoaderRoute: typeof AuthenticatedFinancePayableRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/bank-accounts': {
      id: '/_authenticated/finance/bank-accounts'
      path: '/bank-accounts'
      fullPath: '/finance/bank-accounts'
      preLoaderRoute: typeof AuthenticatedFinanceBankAccountsRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/b2b/accounts': {
      id: '/_authenticated/b2b/accounts'
      path: '/b2b/accounts'
      fullPath: '/b2b/accounts'
      preLoaderRoute: typeof AuthenticatedB2bAccountsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/security': {
      id: '/_authenticated/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AuthenticatedAdminSecurityRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/role-manager': {
      id: '/_authenticated/admin/role-manager'
      path: '/role-manager'
      fullPath: '/admin/role-manager'
      preLoaderRoute: typeof AuthenticatedAdminRoleManagerRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/companies': {
      id: '/_authenticated/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AuthenticatedAdminCompaniesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit-logs': {
      id: '/_authenticated/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/shop/account/orders/$id': {
      id: '/shop/account/orders/$id'
      path: '/$id'
      fullPath: '/shop/account/orders/$id'
      preLoaderRoute: typeof ShopAccountOrdersIdRouteImport
      parentRoute: typeof ShopAccountOrdersRoute
    }
    '/_authenticated/b2b/accounts/$id': {
      id: '/_authenticated/b2b/accounts/$id'
      path: '/$id'
      fullPath: '/b2b/accounts/$id'
      preLoaderRoute: typeof AuthenticatedB2bAccountsIdRouteImport
      parentRoute: typeof AuthenticatedB2bAccountsRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditLogsRoute: typeof AuthenticatedAdminAuditLogsRoute
  AuthenticatedAdminCompaniesRoute: typeof AuthenticatedAdminCompaniesRoute
  AuthenticatedAdminRoleManagerRoute: typeof AuthenticatedAdminRoleManagerRoute
  AuthenticatedAdminSecurityRoute: typeof AuthenticatedAdminSecurityRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditLogsRoute: AuthenticatedAdminAuditLogsRoute,
  AuthenticatedAdminCompaniesRoute: AuthenticatedAdminCompaniesRoute,
  AuthenticatedAdminRoleManagerRoute: AuthenticatedAdminRoleManagerRoute,
  AuthenticatedAdminSecurityRoute: AuthenticatedAdminSecurityRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedFinanceRouteChildren {
  AuthenticatedFinanceBankAccountsRoute: typeof AuthenticatedFinanceBankAccountsRoute
  AuthenticatedFinancePayableRoute: typeof AuthenticatedFinancePayableRoute
  AuthenticatedFinanceReceivableRoute: typeof AuthenticatedFinanceReceivableRoute
  AuthenticatedFinanceTransactionsRoute: typeof AuthenticatedFinanceTransactionsRoute
  AuthenticatedFinanceIndexRoute: typeof AuthenticatedFinanceIndexRoute
}

const AuthenticatedFinanceRouteChildren: AuthenticatedFinanceRouteChildren = {
  AuthenticatedFinanceBankAccountsRoute: AuthenticatedFinanceBankAccountsRoute,
  AuthenticatedFinancePayableRoute: AuthenticatedFinancePayableRoute,
  AuthenticatedFinanceReceivableRoute: AuthenticatedFinanceReceivableRoute,
  AuthenticatedFinanceTransactionsRoute: AuthenticatedFinanceTransactionsRoute,
  AuthenticatedFinanceIndexRoute: AuthenticatedFinanceIndexRoute,
}

const AuthenticatedFinanceRouteWithChildren =
  AuthenticatedFinanceRoute._addFileChildren(AuthenticatedFinanceRouteChildren)

interface AuthenticatedProductsRouteChildren {
  AuthenticatedProductsProductIdRoute: typeof AuthenticatedProductsProductIdRoute
}

const AuthenticatedProductsRouteChildren: AuthenticatedProductsRouteChildren = {
  AuthenticatedProductsProductIdRoute: AuthenticatedProductsProductIdRoute,
}

const AuthenticatedProductsRouteWithChildren =
  AuthenticatedProductsRoute._addFileChildren(
    AuthenticatedProductsRouteChildren,
  )

interface AuthenticatedB2bAccountsRouteChildren {
  AuthenticatedB2bAccountsIdRoute: typeof AuthenticatedB2bAccountsIdRoute
}

const AuthenticatedB2bAccountsRouteChildren: AuthenticatedB2bAccountsRouteChildren =
  {
    AuthenticatedB2bAccountsIdRoute: AuthenticatedB2bAccountsIdRoute,
  }

const AuthenticatedB2bAccountsRouteWithChildren =
  AuthenticatedB2bAccountsRoute._addFileChildren(
    AuthenticatedB2bAccountsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCategoriesRoute: typeof AuthenticatedCategoriesRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDealersRoute: typeof AuthenticatedDealersRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRouteWithChildren
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedInventoryTxRoute: typeof AuthenticatedInventoryTxRoute
  AuthenticatedMembersRoute: typeof AuthenticatedMembersRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRouteWithChildren
  AuthenticatedPurchasesRoute: typeof AuthenticatedPurchasesRoute
  AuthenticatedReceivingRoute: typeof AuthenticatedReceivingRoute
  AuthenticatedRlsTestRoute: typeof AuthenticatedRlsTestRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRoute
  AuthenticatedUserRolesRoute: typeof AuthenticatedUserRolesRoute
  AuthenticatedVendorsRoute: typeof AuthenticatedVendorsRoute
  AuthenticatedWarehousesRoute: typeof AuthenticatedWarehousesRoute
  AuthenticatedB2bAccountsRoute: typeof AuthenticatedB2bAccountsRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCategoriesRoute: AuthenticatedCategoriesRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDealersRoute: AuthenticatedDealersRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRouteWithChildren,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedInventoryTxRoute: AuthenticatedInventoryTxRoute,
  AuthenticatedMembersRoute: AuthenticatedMembersRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRouteWithChildren,
  AuthenticatedPurchasesRoute: AuthenticatedPurchasesRoute,
  AuthenticatedReceivingRoute: AuthenticatedReceivingRoute,
  AuthenticatedRlsTestRoute: AuthenticatedRlsTestRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRoute,
  AuthenticatedUserRolesRoute: AuthenticatedUserRolesRoute,
  AuthenticatedVendorsRoute: AuthenticatedVendorsRoute,
  AuthenticatedWarehousesRoute: AuthenticatedWarehousesRoute,
  AuthenticatedB2bAccountsRoute: AuthenticatedB2bAccountsRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ShopAccountOrdersRouteChildren {
  ShopAccountOrdersIdRoute: typeof ShopAccountOrdersIdRoute
}

const ShopAccountOrdersRouteChildren: ShopAccountOrdersRouteChildren = {
  ShopAccountOrdersIdRoute: ShopAccountOrdersIdRoute,
}

const ShopAccountOrdersRouteWithChildren =
  ShopAccountOrdersRoute._addFileChildren(ShopAccountOrdersRouteChildren)

interface ShopAccountRouteChildren {
  ShopAccountAddressesRoute: typeof ShopAccountAddressesRoute
  ShopAccountOrdersRoute: typeof ShopAccountOrdersRouteWithChildren
  ShopAccountProfileRoute: typeof ShopAccountProfileRoute
  ShopAccountIndexRoute: typeof ShopAccountIndexRoute
}

const ShopAccountRouteChildren: ShopAccountRouteChildren = {
  ShopAccountAddressesRoute: ShopAccountAddressesRoute,
  ShopAccountOrdersRoute: ShopAccountOrdersRouteWithChildren,
  ShopAccountProfileRoute: ShopAccountProfileRoute,
  ShopAccountIndexRoute: ShopAccountIndexRoute,
}

const ShopAccountRouteWithChildren = ShopAccountRoute._addFileChildren(
  ShopAccountRouteChildren,
)

interface ShopRouteChildren {
  ShopAccountRoute: typeof ShopAccountRouteWithChildren
  ShopCheckoutRoute: typeof ShopCheckoutRoute
  ShopProductsRoute: typeof ShopProductsRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ShopCategorySlugRoute: typeof ShopCategorySlugRoute
  ShopProductIdRoute: typeof ShopProductIdRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopAccountRoute: ShopAccountRouteWithChildren,
  ShopCheckoutRoute: ShopCheckoutRoute,
  ShopProductsRoute: ShopProductsRoute,
  ShopIndexRoute: ShopIndexRoute,
  ShopCategorySlugRoute: ShopCategorySlugRoute,
  ShopProductIdRoute: ShopProductIdRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShopRoute: ShopRouteWithChildren,
  TwoFactorRoute: TwoFactorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
